name: Build Project

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
      - linux
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (nasm & binutils)
        run: |
          make deps

      - name: Run build script
        run: |
          make
        continue-on-error: false
