name: Build Project

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
      - linux
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies (nasm & binutils)
        run: |
          sudo apt update
          sudo apt install -y binutils nasm gcc

      - name: Run build script
        run: |
          chmod +x ./build.sh
          ./build.sh
        continue-on-error: false
